# Nixpacks configuration for Railway

[phases.setup]
nixPkgs = ["python311", "gcc"]

[phases.install]
cmds = ["pip install --upgrade pip", "pip install -r requirements.txt"]

[start]
cmd = "gunicorn frontend.app:app --bind 0.0.0.0:$PORT --timeout 120 --workers 1 --threads 2 --log-level info"