services:
  - type: web
    name: notionflow
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --config gunicorn_config.py app:app
    plan: free
    healthCheckPath: /health
    envVars:
      - key: RENDER
        value: "true"
      - key: FLASK_ENV
        value: "production"